### ISSUE TITLE
Homecoming Wiki

### ISSUE THREAD

**Issue by damerell** [n15g/coh-content-db-homecoming#113]
There is now a fork of the Paragon Wiki at https://hcwiki.cityofheroes.dev/wiki/Main_Page

We are working on fixing badges which have changed on Homecoming. This is a large task, but I submit that linking to the HC Wiki is at least no worse than linking to the Paragon Wiki for any given badge.

Please, can the links on pages here be changed?

**Comment by n15g** [comment]
There's two ways to go about this; 
1: Replace the existing paragon wiki links with the new wiki; This is the easiest as a global search-and-replace will do most of the work for us, but I'd only want to do this if the new wiki is stable; Mainly the url. If the domain or the context is likely to change in the near future it might be better to wait.

2: Add the new links in addition to the paragon wiki links. This is probably my preference, but it would be a much bigger job to add the links in to the 2000 or so files needed.

**Comment by damerell** [comment]
Regrettably, I'm not the operator of the new Wiki; that's "Michiyo" on Discord and the forums, who might be able to comment further.

However, I submit if global search-and-replace can do the heavy lifting, then if the new Wiki implodes it's no great loss - just revert the relevant commit.

**Comment by AboveTheChemist** [comment]
I noticed that some badges (for example, at least some of the Veteran badges) have no links at all, so if a global search-and-replace is eventually utilized, it might help to check for non-existant links in the process.

There's also now a 'club' for the unofficial homecoming wiki (UHW) on the forums if you'd like to take a peek and/or join: [https://forums.homecomingservers.com/clubs/2-unofficial-homecoming-wiki/](https://forums.homecomingservers.com/clubs/2-unofficial-homecoming-wiki/)

**Comment by AboveTheChemist** [comment]
Just wanted to give this a bump. The HC wiki has been going strong for almost a year and still receives regular maintenance/updates so I think it is reasonable to assume by this point that it is stable. When the opportunity arises, I have been updating the old Paragon Wiki links with HC wiki links when I edit badges, but I have only updated a handful.
