### ISSUE TITLE
VIP/Destined One and Praetoria's Son/Daughter

### ISSUE THREAD

**Issue by Hard-Eight** [n15g/coh-content-db-homecoming#119]
At current, these are two separate badges but they should be the same. V.I.P. is the hero version, Destined One is the Villain Version, and Praetoria's Son/Daughter is the Praetorian version.

**Comment by n15g** [comment]
I can merge these two badges, but it'll result in anyone who has it collected under the merged id to have to go and re-select it for those character. I'll add a note to that effect to the patch notes.

**Comment by n15g** [comment]
Actually, it looks like these were split intentionally in #107, since it has different setTitle ids and a different placement in the list for praetorian characters vs primal.
