### ISSUE TITLE
Firstly: What? Secondly: How?

### ISSUE THREAD

**Issue by Dramatus4000** [n15g/coh-content-db-homecoming#152]
Is there a easy to follow instruction section to connect my game data with this resource? I am inexperienced with coding so I am not sure what a lot of this means. :)

**Comment by n15g** [comment]
For the what: this particular project is just a dataset containing information on all the badges in CoH: Homecoming that can be used by other projects that need that data.

For the how, however, from you're question I'm guessing you're more interested in badge tracking, etc? That's where the badger project comes in... and if you're just interested in using it to track badges all you need is the link to the app itself: https://n15g.github.io/badger/

From that app, click the Characters tab up the top and either start checking the badges off that you have on each character page, or if you want a bit more of an automated experience (albeit a bit more work to set up), click the 'Log Parser' button on the characters screen and follow the help guide.


If I've got the assumption wrong though and you're actually looking to use the badge data from this project in another project, then feel free to leave some context and I'll point you in the right direction.

**Comment by Dramatus4000** [comment]
Thanks so much!
