### ISSUE TITLE
New badges for Issue 27 Page 4

### ISSUE THREAD

**Issue by AboveTheChemist** [n15g/coh-content-db-homecoming#154]
I've got the ten new badges for i27p4 added to my local branch and ready to merge (along with updating the category indices so the badges show up in the proper order). I am going to wait until closer to when (or maybe immediately after) i27p4 goes live to submit the pull request for it, just in case there are any last minute changes. I just want to let anyone else know so there wouldn't be any duplicated effort to update for i27p4.

If anyone knows of any other badges that need updating, feel free to let me know and I will add those to my local branch.

**Comment by n15g** [comment]
Awesome!
Let me know when you're ready to push those and I'll update the main branch 👍
