### ISSUE TITLE
HC wiki has a new URL

### ISSUE THREAD

**Issue by AboveTheChemist** [n15g/coh-content-db-homecoming#164]
The URL of the homecoming wiki has changed

The former URL was:

https://hcwiki.cityofheroes.dev

The new URL is:

https://homecoming.wiki

I have been replacing the old URL with the new one where I can, but if it is possible to do a global search/replace to update the URLs to the new one, that would be awesome. The old URL still redirects to the new (for now, unsure if that will change), but it might be better long-term to update to the new URL.

Thanks!

ATC

**Comment by n15g** [comment]
Yep, should be relatively easy. I'll update that this morning.

**Comment by n15g** [comment]
There was only 1578 files to change 😆
