### ISSUE TITLE
need help?

### ISSUE THREAD

**Issue by chuckv3** [n15g/coh-content-db-homecoming#166]
I think I have all the badges for the Labyrinth (Issue 28) on TinkerBell on Homecoming/Reunion. Can I help by adding JSON files for those? Or can I take a stab at it and send it to one of you folks with more experience?

**Comment by chuckv3** [comment]
This is what I have. Details about how to earn them are in teh patch notes iirc.

Bound by NDA
You were successful in exposing ---- ---------- for having stolen ------- ---- from ---- ----- and using it to ---- ----- --- ------. You just can't legally talk about it.

Conqueror of the Labyrinth
You have proven your prowess by having not only explored, but also conquered everything that stood in your path within the maze of corridors known as the Labyrinth of Fog. This badge unlocks the ability to teleport from the Labyrinth of Fog's lobby to the Core of the Labyrinth

Greek Philosopher
The origin behind the Labyrinth of Fog has been obscured for ages, but you've recently discovered evidence that suggests the labyrinth was created to imprison an ancient calamity that once befell the islands of Greece.

Slayer of the Minotaur
Historians insisted it couldn't be done, that The Minotaur In The Fog could not be bested in combat, but you've done just that. You've proven yourself worthy to stand shoulder-to-shoulder with the greatest ancient heroes of myth.

Phantom Gladiator
The Labryinth's Gladiators In The Fog are a curious phenomenon. This legion of immortal warriors compete in an eternal blood sport to determine who is the strongest amongst them, but not one was found worthy of taking you down.

Lab Rat
Whilst exploring the Labyrinth of Fog, you navigated a maze known as the Endless Colonnade. You can't help but feel like a lab rat, running a maze for some unseen intelligence's amusement...

Malevolent Intoxication
The Labyrinth of Fog is an unnatural dungeon where a mythical fog, steeped in malevolence, coagulates of its own volition, and you've taken advantage of the opportunity to claim their power for yourself.

Hidden In The Fog
The Labyrinth of Fog is an endless maze constructed from the amalgamation of memories taken from those who have entered the maze. Some speak of finding lost secrets, long forgotten, laying hidden amongst the fog, and that those who surrender themselves to the labyrinth are in a position to glean forbidden knowledge.

Between Realities
You've spent a significant amount of time shifting between the spatial overlaps of the First Ward and Night Ward. With experience, you've learned of a method to manipulate the magics used by the Light & Shadowed Paths to define and utilize spatial jump points of your own.

Multifaceted
You've walked too many roads of life to count, and your experience affords you a position of reflection and wisdom. You've completed countless Alignment Tip missions and made many moral decisions.

Adept
The amount of moral options open to you sometimes leads to complulsary or contradictory decisions, but that's part of the freedom to make choices. You've completed several Alignment Tip missions and made some moral decisions.

Uncommitted
There's so many options sometimes in life, you can't help but have a difficult time choosing. You've completed a few Alignment Tip missions and made a couple moral decisions.

Protector of Paragon City
You have shown true dedication to the protection of Paragon City, without sacrificing the morals that the city is founded and established on.

Deep Strike Agent
You have successfully taken part in many of the most impactful operations and Strike Forces executed by Arachnos and their 'Destined Ones'. You can break free from many effects out of sheer spite, due to your remarkable tenacity.

**Comment by chuckv3** [comment]
images can maybe be scraped from here?
![screenshot_240730-03-56-43](https://github.com/user-attachments/assets/a6d8b107-6363-4d81-9f2b-a8d0523ab7ba)
![screenshot_240730-03-56-46](https://github.com/user-attachments/assets/764ea84f-59c6-4315-89f3-cc27b1f46be7)
![screenshot_240730-03-57-42](https://github.com/user-attachments/assets/3b85d33c-3c33-45f9-a464-4499953529c3)
![screenshot_240730-03-57-53](https://github.com/user-attachments/assets/687fce7a-f178-49fa-a15e-668ac494145b)
![screenshot_240730-03-58-00](https://github.com/user-attachments/assets/e2b8e1a5-2c88-48cd-bf89-f9b39fe5c20d)

**Comment by AboveTheChemist** [comment]
I appreciate the effort but I have more efficient/reliable means of getting the raw badge info and icons. I pull the info from the game files themselves as I am working on updating other mods.

**Comment by n15g** [comment]
Hey, I should have some time over the weekend to add these in. I haven't been paying attention to the game, ATC has been doing all the work for ages now 😆 
I can put something together if ATC is busy, but the images from the game files would be better than manually cropping. Would probably also need the badge type for each, and where it sits in the natural badge order.
