### ISSUE TITLE
Ouroboros badge level ranges

### ISSUE THREAD

**Issue by n15g** [n15g/coh-content-db-homecoming#2]
> The second level range on the Ouroborous badges says 15-19, but the spreadsheet says 16-19 (which I assume is correct since the first range is 1-15). - darkgob

These are all over the place... The badge text doesn't match the oro ranges, and the wiki data is even more inconsistent... The spreadsheet was using the wiki values, but I deferred to the badge text for the app.

Can someone confirm what the actual level ranges are for granting the badges?

**Comment by blhylton** [comment]
Running a mission that exemplars you to level 15 awards the first set of badges, so the second set is 16 to 19 (presumably, I couldn't find a mission that exemps to 16 to test with).

To make things even more confusing, the level ranges in Ouroboros have nothing to do with the badges. The only thing that matters is the level that you're exemped to.

**Comment by n15g** [comment]
That makes more sense... there's no overlap that way, even if the badge text is incorrect >_<

I'll update those ranges in 0.5.0

**Comment by blhylton** [comment]
Honestly, the ranges are just really strange. Let me play around with some edge cases on a character I don't usually badge with and see what earns what. Keep this issue open and I'll report back as I figure out more.

**Comment by n15g** [comment]
Will do, thanks!

**Comment by blhylton** [comment]
Okay, so in the past hour, I've gotten a badge from the second set in a level 20 mission and from the third set in a level 25. It's beginning to look like the ranges end on multiples of 5 all the way up. This would mean that all the badge text is incorrect save for the first and the last one.

**Comment by n15g** [comment]
Consistently inconsistent you could say...
