### ISSUE TITLE
Ordering is a mess

### ISSUE THREAD

**Issue by n15g** [n15g/coh-content-db-homecoming#4]
I don't have enough badges on Homecoming to know the proper ordering for a lot of the badges. I could definitely use some input once the rest of the badges are defined to get them into the canonical order.

Exploration: Done
History: Done
Accomplishment: Done
Achievement: Done
Accolade:
Gladiator:
Veteran: Done
PvP:
Invention: Done
Defeat:
Event:
Ouroboros:
Consignment: Done
Day Job:
AE:

**Comment by blhylton** [comment]
How are you intending on ordering them? Just by the order they're imported into their "index" files or were you looking to add a field to sort by?

**Comment by n15g** [comment]
The index int the badge array is used to order them at the moment.
Originally I had a sort field... but when a new badge is added... updating 1000 badge files seemed less-than-fun...

**Comment by blhylton** [comment]
https://github.com/blhylton/coh-content-db-homecoming/tree/improvement/badge-ordering

Exploration badges complete.

**Comment by n15g** [comment]
I see you had the history ones done as well, I merged them both in. Thanks!

**Comment by blhylton** [comment]
Yeah, I just pushed Accomplishment and Achievement to that branch. I was going to get them all in good shape and do a PR, but that works too :P I'll keep updating that same branch.

**Comment by n15g** [comment]
I'll hold the next build off until you're ready. The ordering is the main thing making me hold off on a 1.0 release, so it'll be great to have this done... thanks a bunch for the effort!

**Comment by blhylton** [comment]
Veteran badges are already in order FYI, so there won't be a commit for those.

**Comment by blhylton** [comment]
Same for invention and consignment.

**Comment by n15g** [comment]
Excellent point... I've updated the first comment.

**Comment by blhylton** [comment]
Just pushed all except PVP and Day Jobs live. Those will require me to actually get more of them to get the lists in order. Day Jobs looks like it is close based off what I have already, but I'm not comfortable saying that it's complete. Unfortunately, it changed from live, so the old lists don't help.

**Comment by n15g** [comment]
Close enough is good enough for me!
I have almost all of them on HC (My most complete badge set is the badges for not playing... go figure)... I'll check them next time I get a chance.
I'll merge them in as-is though... it's easy enough to correct later.

Raise a PR and I'll merge it in. I noticed that it didn't add you to contributors when I squashed it pulling from my end.

**Comment by blhylton** [comment]
PR is up https://github.com/n15g/coh-content-db-homecoming/pull/28

**Comment by n15g** [comment]
Merged and thank you!

That is a good one to have resolved... I've had my fill of tedious data entry for at least this month, so I was dreading doing this one XD
